-- _advance_non_mlp_playoff_bracket()
-- Trigger function that fires when a tournament_matches row's status flips
-- to 'completed'. If the match belongs to a playoff round (quarterfinals or
-- semifinals) of a non-MLP round_robin / pool_play tournament, and the
-- whole round is now complete, seeds the next round:
--
--   Quarterfinals → Semifinals (pair winners outside-in: mo=0 with mo=N-1,
--                                                       mo=1 with mo=N-2, …)
--   Semifinals    → Finals     (pair the 2 SF winners)
--   Finals        → (terminal — auto-close trigger handles tournament status)
--
-- This complements the existing `_advance_single_elim_bracket()` trigger,
-- which only handles `single_elimination` / `double_elimination` larger
-- formats. The new trigger fires for round_robin / pool_play tournaments
-- whose playoff brackets were generated by `generate_playoff_bracket()`.
--
-- Third Place Match (top_2 case) is independent: it's already created at
-- bracket-gen time and doesn't need advancement.

create or replace function public._advance_non_mlp_playoff_bracket()
returns trigger language plpgsql security definer as $$
declare
  v_format          text;
  v_match_type      text;
  v_round_type      text;
  v_round_number    integer;
  v_uncompleted     integer;
  v_winners         record;
  v_next_round_id   uuid;
  v_next_round_num  integer;
  v_next_round_type text;
  v_next_label      text;
  v_count           integer;
  v_i               integer;
  v_w1              record;
  v_w2              record;
begin
  if new.status <> 'completed' then return new; end if;
  if TG_OP = 'UPDATE' and old.status = 'completed' then return new; end if;

  select format, match_type
    into v_format, v_match_type
    from public.tournaments
   where id = new.tournament_id;
  if v_format not in ('round_robin', 'pool_play') then return new; end if;

  select round_type, round_number
    into v_round_type, v_round_number
    from public.tournament_rounds
   where id = new.round_id;
  if v_round_type not in ('quarterfinals', 'semifinals') then return new; end if;

  -- Wait until the whole round is complete
  select count(*) into v_uncompleted
    from public.tournament_matches
   where round_id = new.round_id
     and status <> 'completed';
  if v_uncompleted > 0 then return new; end if;

  -- Determine the next round type
  if v_round_type = 'quarterfinals' then
    v_next_round_type := 'semifinals';
    v_next_label      := 'Semifinals';
  else
    v_next_round_type := 'finals';
    v_next_label      := 'Finals';
  end if;

  -- Idempotent: skip if the next round already exists
  if exists (
    select 1 from public.tournament_rounds
     where tournament_id = new.tournament_id
       and round_type = v_next_round_type
  ) then
    return new;
  end if;

  -- Count winners
  select count(*) into v_count
    from public.tournament_matches
   where round_id = new.round_id
     and winner_team in ('team1', 'team2');
  if v_count < 2 then return new; end if;

  v_next_round_num := coalesce(v_round_number, 1000) + 100;
  insert into public.tournament_rounds (tournament_id, round_number, label, round_type)
    values (new.tournament_id, v_next_round_num, v_next_label, v_next_round_type)
    returning id into v_next_round_id;

  -- Outside-in pairing: mo[i] paired with mo[N-1-i], so seed 1 stays on
  -- one half and seed 2 stays on the other half until the final.
  for v_i in 0..(v_count / 2 - 1) loop
    with ordered as (
      select tm.*,
             row_number() over (order by match_order, id) - 1 as rn
        from public.tournament_matches tm
       where tm.round_id = new.round_id
         and tm.winner_team in ('team1', 'team2')
    )
    select * into v_w1 from ordered where rn = v_i;

    with ordered as (
      select tm.*,
             row_number() over (order by match_order, id) - 1 as rn
        from public.tournament_matches tm
       where tm.round_id = new.round_id
         and tm.winner_team in ('team1', 'team2')
    )
    select * into v_w2 from ordered where rn = v_count - 1 - v_i;

    if v_w1 is null or v_w2 is null then continue; end if;
    -- Skip the degenerate same-match pairing in case v_count=1
    if v_w1.id = v_w2.id then continue; end if;

    insert into public.tournament_matches (
      tournament_id, round_id, match_order, match_type,
      team1_player1,
      team1_player2,
      team2_player1,
      team2_player2,
      status
    )
    values (
      new.tournament_id,
      v_next_round_id,
      v_i,
      coalesce(v_match_type, 'singles'),
      case when v_w1.winner_team = 'team1' then v_w1.team1_player1 else v_w1.team2_player1 end,
      case when v_w1.winner_team = 'team1' then v_w1.team1_player2 else v_w1.team2_player2 end,
      case when v_w2.winner_team = 'team1' then v_w2.team1_player1 else v_w2.team2_player1 end,
      case when v_w2.winner_team = 'team1' then v_w2.team1_player2 else v_w2.team2_player2 end,
      'pending'
    );
  end loop;

  return new;
end;
$$;

grant execute on function public._advance_non_mlp_playoff_bracket() to authenticated;

drop trigger if exists trg_advance_non_mlp_playoff_bracket on public.tournament_matches;
create trigger trg_advance_non_mlp_playoff_bracket
  after insert or update of status on public.tournament_matches
  for each row execute procedure public._advance_non_mlp_playoff_bracket();

notify pgrst, 'reload schema';
