-- Min players + registration waitlist.
--
-- 1. tournaments.min_players — displayed on the detail page, enforced
--    client-side at bracket lock-in (the bracket is generated by the app,
--    so the app is the natural gate).
-- 2. Waitlist: once approved players reach max_players, new self-requests
--    are flipped to status 'waitlisted' by a BEFORE INSERT trigger (the
--    client keeps inserting the default 'pending'). When a spot opens —
--    an approved player leaves / is removed, or the admin raises
--    max_players — the oldest waitlisted registrations are promoted back
--    to 'pending' (normal admin review), one per free spot, with
--    notifications to the promoted player and the tournament creator.
-- 3. Capacity guard: transitions to 'approved' beyond max_players are
--    rejected with a clear error, so invites/approvals can't overshoot.
--
-- RLS note: the hardened "Users can register themselves" INSERT policy
-- pinned status = 'pending'. WITH CHECK runs AFTER before-triggers, so the
-- waitlist flip would violate it — the policy is recreated to accept both
-- 'pending' and 'waitlisted'. New-row column references stay hoisted
-- outside the subqueries (see the name-capture pitfall in CLAUDE.md).

alter table public.tournaments
  add column if not exists min_players integer
  check (min_players is null or min_players >= 2);

alter table public.tournaments
  drop constraint if exists tournaments_min_max_players_check;
alter table public.tournaments
  add constraint tournaments_min_max_players_check
  check (min_players is null or max_players is null or min_players <= max_players);

alter table public.tournament_registrations
  drop constraint tournament_registrations_status_check;
alter table public.tournament_registrations
  add constraint tournament_registrations_status_check
  check (status = any (array['pending'::text, 'approved'::text, 'rejected'::text, 'waitlisted'::text]));

-- ── Waitlist flip on insert ─────────────────────────────────────────────
create or replace function public._waitlist_if_full()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_max      integer;
  v_approved integer;
  v_position integer;
  v_name     text;
begin
  select t.max_players into v_max from public.tournaments t where t.id = new.tournament_id;

  -- Only self-requests are subject to the waitlist; invites and the
  -- creator bootstrap are admin-driven (the approve guard still applies).
  if new.invited_by is not null or new.status <> 'pending' then
    return new;
  end if;
  if v_max is null then return new; end if;

  select count(*) into v_approved
    from public.tournament_registrations r
   where r.tournament_id = new.tournament_id and r.status = 'approved';

  if v_approved >= v_max then
    new.status := 'waitlisted';
    select count(*) + 1 into v_position
      from public.tournament_registrations r
     where r.tournament_id = new.tournament_id and r.status = 'waitlisted';
    select t.name into v_name from public.tournaments t where t.id = new.tournament_id;
    insert into public.notifications (user_id, title, body, type, entity_id, entity_type)
    values (
      new.user_id,
      '⏳ You''re on the waitlist',
      format('"%s" is full (%s players max). You''re #%s on the waitlist — you''ll be notified when a spot opens.',
             coalesce(v_name, 'Tournament'), v_max, v_position),
      'tournament', new.tournament_id, 'tournament'
    );
  end if;
  return new;
end;
$$;
revoke execute on function public._waitlist_if_full() from public, anon, authenticated;

drop trigger if exists trg_waitlist_if_full on public.tournament_registrations;
create trigger trg_waitlist_if_full
  before insert on public.tournament_registrations
  for each row execute function public._waitlist_if_full();

-- ── Capacity guard on approval ──────────────────────────────────────────
create or replace function public._block_approve_over_capacity()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_max      integer;
  v_approved integer;
begin
  if new.status <> 'approved' then return new; end if;
  if tg_op = 'UPDATE' and old.status = 'approved' then return new; end if;

  select t.max_players into v_max from public.tournaments t where t.id = new.tournament_id;
  if v_max is null then return new; end if;

  select count(*) into v_approved
    from public.tournament_registrations r
   where r.tournament_id = new.tournament_id
     and r.status = 'approved'
     and r.id <> new.id;

  if v_approved >= v_max then
    raise exception 'Tournament is full (max % players). Remove a player or raise Max Players first.', v_max;
  end if;
  return new;
end;
$$;
revoke execute on function public._block_approve_over_capacity() from public, anon, authenticated;

drop trigger if exists trg_block_approve_over_capacity on public.tournament_registrations;
create trigger trg_block_approve_over_capacity
  before insert or update on public.tournament_registrations
  for each row execute function public._block_approve_over_capacity();

-- ── Waitlist promotion when a spot opens ────────────────────────────────
-- Promotes the oldest waitlisted registrations back to 'pending' (normal
-- admin review), one per free approved slot. Fires when an approved player
-- leaves / is removed and when max_players is raised; only while the
-- tournament is still in registration.
create or replace function public._promote_tournament_waitlist(p_tournament_id uuid)
returns void language plpgsql security definer set search_path = public as $$
declare
  v_t        record;
  v_approved integer;
  v_free     integer;
  v_promoted integer := 0;
  v_reg      record;
begin
  select id, name, status, max_players, created_by into v_t
    from public.tournaments where id = p_tournament_id;
  if v_t.id is null or v_t.status <> 'registration' then return; end if;
  if v_t.max_players is null then
    -- Limit removed entirely: everyone waitlisted goes back to pending.
    v_free := null;
  else
    select count(*) into v_approved
      from public.tournament_registrations r
     where r.tournament_id = p_tournament_id and r.status = 'approved';
    v_free := greatest(0, v_t.max_players - v_approved);
    if v_free = 0 then return; end if;
  end if;

  for v_reg in
    select r.id, r.user_id
      from public.tournament_registrations r
     where r.tournament_id = p_tournament_id and r.status = 'waitlisted'
     order by r.registered_at asc
  loop
    exit when v_free is not null and v_promoted >= v_free;
    update public.tournament_registrations set status = 'pending' where id = v_reg.id;
    insert into public.notifications (user_id, title, body, type, entity_id, entity_type)
    values (
      v_reg.user_id,
      '🎟️ A spot opened up!',
      format('You''re off the waitlist for "%s" — your request is now pending admin review.', v_t.name),
      'tournament', p_tournament_id, 'tournament'
    );
    v_promoted := v_promoted + 1;
  end loop;

  if v_promoted > 0 then
    insert into public.notifications (user_id, title, body, type, entity_id, entity_type)
    values (
      v_t.created_by,
      '🎟️ Waitlist moved',
      format('%s waitlisted player%s for "%s" %s now pending your review.',
             v_promoted, case when v_promoted = 1 then '' else 's' end,
             v_t.name, case when v_promoted = 1 then 'is' else 'are' end),
      'tournament', p_tournament_id, 'tournament'
    );
  end if;
end;
$$;
revoke execute on function public._promote_tournament_waitlist(uuid) from public, anon, authenticated;

create or replace function public._promote_waitlist_on_reg_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  -- A spot opens when an approved registration is deleted or stops being
  -- approved (withdrawn, removed, rejected).
  if tg_op = 'DELETE' then
    if old.status = 'approved' then perform public._promote_tournament_waitlist(old.tournament_id); end if;
    return old;
  end if;
  if old.status = 'approved' and new.status <> 'approved' then
    perform public._promote_tournament_waitlist(new.tournament_id);
  end if;
  return new;
end;
$$;
revoke execute on function public._promote_waitlist_on_reg_change() from public, anon, authenticated;

drop trigger if exists trg_promote_waitlist_on_reg_change on public.tournament_registrations;
create trigger trg_promote_waitlist_on_reg_change
  after update or delete on public.tournament_registrations
  for each row execute function public._promote_waitlist_on_reg_change();

create or replace function public._promote_waitlist_on_capacity_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.max_players is distinct from old.max_players then
    perform public._promote_tournament_waitlist(new.id);
  end if;
  return new;
end;
$$;
revoke execute on function public._promote_waitlist_on_capacity_change() from public, anon, authenticated;

drop trigger if exists trg_promote_waitlist_on_capacity_change on public.tournaments;
create trigger trg_promote_waitlist_on_capacity_change
  after update on public.tournaments
  for each row execute function public._promote_waitlist_on_capacity_change();

-- ── RLS: accept the waitlist flip on self-inserts ───────────────────────
drop policy if exists "Users can register themselves" on public.tournament_registrations;
create policy "Users can register themselves" on public.tournament_registrations
  for insert with check (
    auth.uid() = user_id
    and invited_by is null
    and (
      -- creator bootstrap (approved admin at creation)
      exists (
        select 1 from public.tournaments t
        where t.id = tournament_registrations.tournament_id
          and t.status = 'registration'
          and t.created_by = auth.uid()
      )
      or (
        -- self-request into an open request-mode tournament; the BEFORE
        -- trigger may flip 'pending' to 'waitlisted' when full, and WITH
        -- CHECK sees the flipped row.
        status in ('pending', 'waitlisted')
        and role = 'member'
        and exists (
          select 1 from public.tournaments t
          where t.id = tournament_registrations.tournament_id
            and t.status = 'registration'
            and t.registration_mode = 'request'
            and (t.registration_closes_at is null or now() < t.registration_closes_at)
        )
      )
    )
  );
